# RIGHT OF SET-OFF

## Set-off Calculation.

(a) When a Team ("First Team") terminates a Player Contract ("First Contract") in circumstances where the First Team, following the termination, continues to be liable for unearned Base Compensation (i.e., unearned as of the date of the termination) called for by the First Contract (including any unearned Deferred Base Compensation), the First Team's liability for such unearned Base Compensation shall be reduced pro rata by a portion of the compensation earned by the player (for services as a player) from any professional basketball team or teams (the "Subsequent Team(s)") during each Salary Cap Year covered by the First Contract (including, but not limited to, compensation earned but not paid during such period). The First Team may require that the player provide the First Team with evidence (such as a copy of the player's new contract) of the compensation to be earned by the player with any Subsequent Team(s). The reduction in the First Team's liability shall be calculated for each Salary Cap Year (or partial Salary Cap Year) as follows:
    
    STEP 1: Calculate the total compensation earned by the player (for services as a player) from the Subsequent Team(s) during the Salary Cap Year (or partial Salary Cap Year).
    
    STEP 2: Subtract from the result in Step 1 (i) if the player had zero (0) Years of Service at the time the First Contract was terminated, the Minimum Annual Salary applicable to such player for the Salary Cap Year in which the First Contract was terminated, or (ii) if the player had one (1) or more Years of Service at the time the First Contract was terminated, the Minimum Annual Salary applicable to a player with one (1) Year of Service for the Salary Cap Year in which the First Contract was terminated.
    
    STEP 3: If the result in Step 2 is a negative amount, there is no reduction in the First Team's liability for the relevant Salary Cap Year (or partial Salary Cap Year). If the result in Step 2 is a positive amount, the reduction in the First Team's liability for the relevant Salary Cap Year (or partial Salary Cap Year) shall equal fifty percent (50%) of such amount.
(b) For the purposes of this Article XXVII: (i) a "professional basketball team" shall mean any team in any country that pays money or compensation of any kind to a basketball player for rendering services to such team (other than a reasonable stipend limited to basic living expenses); and (ii) "compensation" earned by a player shall include all forms of compensation (including, without limitation, any non-cash compensation) other than benefits comparable to the type of benefits (e.g., medical and dental insurance) provided to an NBA player in accordance with Article IV above, travel and moving expenses, and any car and housing provided temporarily by a professional basketball team to the player during the period of time for which the player renders services to such team.
(c) Without limiting any other rights the First Team has, in the event a player's compensation is reduced pursuant to this Article XXVII and the Team is unable to affect all or a portion of the reduction through payroll deductions, the NBA shall have the right to direct any Subsequent Team that is an NBA Team to withhold any unrecouped amounts from the player's compensation under his new Uniform Player Contract and remit such amounts to the First Team.

## Successive Terminations.

In the event of successive terminations by NBA Teams of Player Contracts involving the same player, the Team first to terminate shall be entitled to the right of set-off provided for by this Article XXVII until its compensation liability has been eliminated in its entirety, and the right of set-off shall then pass in order to the Team(s) terminating any subsequent Contract(s).

## Deferred Compensation.

In calculating the amount of set-off to which a Team may be entitled pursuant to this Article XXVII, the unearned Deferred Compensation payable to a player for or with respect to a period covered by the terminated Contract shall be discounted on an annual basis by a percentage equal to the prime rate as set by Citibank, N.A. and in effect at the time the agreement providing for such Deferred Compensation was made.

## Waiver of Set-off Right.

A Team and a player may agree in an amendment to an already-existing Player Contract to modify or eliminate the set-off right provided in this Article XXVII, but only pursuant to and to the extent allowed by Article II, Section 3(l).

## Amnesty Players.

In the event a player is waived by a Team ("Team A") pursuant to Article VII, Section 12(f)(5), the player's Contract is claimed by a Team ("Team B") that assumes only partial responsibility for the player's remaining Compensation, the player's Contract is subsequently terminated by Team B, and the player subsequently earns compensation from another professional basketball team triggering a right of set-off under this Article XXVII, the set-off amount shall be allocated among Team A and Team B in proportion to the amount of Base Compensation for the Season in question for which Team A and Team B are responsible.
