# MEDIA RIGHTS

## League Rights.

The Players Association agrees that the NBA, all League-related entities (including, but not limited to, NBA Properties, Inc. and NBA Media Ventures, LLC) that generate BRI and NBA Teams have the right during and after the term of this Agreement to use, exhibit, distribute, or license any performance by the players, under this Agreement or the Uniform Player Contract, in any or all media, formats or forms of exhibition and distribution, whether analog, digital or other, now known or hereafter developed, including, but not limited to, print, tape, disc, computer file, radio, television, motion pictures, other audio-visual and audio works, Internet, broadband platforms, mobile platforms, applications, and other distributions platforms (collectively, "Media").

## No Suit.

The Players Association, for itself and present and future NBA players, covenants not to sue (or finance any suit against) the NBA, all League- related entities (including NBA Properties, Inc. and NBA Media Ventures, LLC) that generate BRI and all NBA Teams, or, any of their respective past, present and future owners (direct and indirect) acting in their capacity as owners of any of the foregoing entities, officers, directors, trustees, employees, agents, attorneys, licensees, successors, heirs, administrators, executors and assigns, with respect to the use, exhibition, distribution, or license, in any or all Media, of any performances by any player rendered under this Agreement or prior collective bargaining agreements, or under Player Contracts made pursuant thereto. The foregoing covenant not to sue shall not apply to any claim that any such use of a performance by a player constitutes an unauthorized endorsement by such player of a third-party brand, product or service ("Endorsement"). For purposes of clarity, and without limitation, it shall not be an Endorsement for the NBA, a League-related entity or an NBA Team to use, or authorize others to use, including, without limitation, in third party advertising and promotional materials, footage and photographs of a player's participation in NBA games or other NBA events that do not unduly focus on, feature, or highlight, such player in a manner that leads the reasonable consumer to believe that such player is a spokesman for, or promoter of, a third-party commercial product or service.

## Reservation of Rights.

The Players Association expressly reserves its rights to bargain collectively on the subject described in Section 1 above at the expiration of this Agreement. Such reservation shall not, however, preclude the NBA from contending that the subject described in Section 1 above is not a mandatory subject of collective bargaining. The right of the NBA, League-related entities and NBA Teams described in Section 1 above is in addition to, and shall not limit nor be deemed to limit, derogate from or otherwise prejudice, any and all rights that any one or all of them have heretofore possessed or enjoyed, do now possess or enjoy or may hereafter possess or enjoy.