# 

## AUTHORIZATION FOR TESTING

|        |                     |
| :----- | :-----------------: |
| To:    | ___________________ |
|        |                     |
| Player | ___________________ |

Please be advised that on __________________________, you were the subject of a meeting or conference call held pursuant to the Anti-Drug Program set forth in Article XXXIII of the Collective Bargaining Agreement between the NBA and the National Basketball Players Association, dated December 8, 2011 (the "Agreement"). Following the meeting or conference call, I authorized the NBA to conduct the testing procedures set forth in the Agreement, and you are hereby directed to submit to those testing procedures, on demand, no more than four (4) times during the next six (6) weeks.

Please be advised that your failure to submit to these procedures may result in substantial penalties, including but not limited to your dismissal and disqualification from the NBA.

|                          |
| :----------------------- |
| ________________________ |
| Independent Expert       |
| Dated:                   |
| ________________________ |

## PROHIBITED SUBSTANCES

A. Drugs of Abuse

- Amphetamine and its analogs (including, but not limited to, methamphetamine and MDMA)
- Cocaine
- LSD
- Opiates (Heroin, Codeine, Morphine)
- Phencyclidine (PCP)

B. Marijuana and its By-Products

C. Steroids, Performance Enhancing Drugs, and Masking Agents (SPEDs)

- Adrafinil
- Aminoglutethimide
- Amiphenazole
- Anastrozole
- Androsta-1,4,6-triene-3,17-dione (also called androstatrienedione or ATD)
- Androstanediol
- Androstanedione
- Androstenediol
- Androstenedione
- Androstene-3,6,17-trione (also called 6-OXO or 4-AT)
- Bolasterone
- Boldenone
- Boldione
- Bromantan
- Calusterone
- Clenbuterol
- Clobenzorex
- Clomiphene
- Clostebol
- Cyclofenil
- Danazol
- Dehydrochloromethyltestosterone
- Dehydroepiandrosterone (DHEA)
- Desoxymethyltestosterone (DMT)
- Dihydrotestosterone
- 4-dihydrotestosterone
- Dromostanolone
- Drostanolone
- Ephedra (also called Ma Huang, Bishop's Tea and Chi Powder)
- Ephedrine
- Epitestosterone
- 13a-ethyl-17a-hydroxygon-4-en-3-one
- Etilefrine
- Ethylestrenol
- Exemestane
- Fencamfamin
- Fenethylline
- Fenfluramine
- Fenproporex
- Fluoxymesterone
- Formebolone
- Formestane (also called 4-hydroxyandrostenedione)
- Fulvestrant
- Furazabol
- Gestrinone
- 18a-homo-17b-hydroxyestr-4-en-3-one
- Human Chorionic Gonadotropin
- Human Growth Hormone
- 4-hydroxytestosterone
- Letrozole
- Mefenorex
- Mestanolone
- Mesterolone
- Methandienone
- Methandriol
- Methasterone
- Methenolone
- Methyldienolone
- 17a-methyl-3b,17b-dihydroxy-5a-androstane
- 17a-methyl-3a,17b-dihydroxy-5a-androstane
- 17a-methyl-3b,17b-dihydroxyandrost-4-ene
- 17a-methyl-1-dihydrotestosterone 
- 17a-methyl-4hydroxynandrolone
- Methylephedrine
- Methylphenidate
- Methyltestosterone
- Methyltrienolone (also called metribolone)
- Mibolerone
- Modafinil
- Nandrolone (also called 19-nortestosterone)
- Nikethamide
- 19-norandrostenediol
- 19-norandrostenedione
- Norbolethone
- Norclostebol
- Norethandrolone
- Norfenfluramine
- Normethandrolone (also called methylnortestosterone or MENT)
- Norpseudoephedrine (also called cathine)
- Oxabolone (also called 4-hydroxy-19-nortestosterone)
- Oxandrolone
- Oxymesterone
- Oxymetholone
- Pemoline
- Pentetrazol
- Phendimetrazine
- Phenmetrazine
- Phentermine
- Phenylpropanolamine (PPA) 
- Probenecid
- Prostanozol
- Pseudoephedrine
- Quinbolone
- Stanozolol
- Stenbolone
- Strychnine
- Testolactone
- Testosterone
- Tetrahydrogestrinone (THG)
- Tibolone
- Trenbolone
- Zeranol
- Zilpaterol

D. Diuretics

- Acetazolamide 
- Amiloride 
- Bendroflumethiazide
- Benzthiazide 
- Bumetanide
- Canrenone
- Chlorothiazide
- Chlorthalidone
- Clopamide
- Cyclothiazide
- Dichlorphenamide
- Ethacrynic Acid
- Flumethiazide
- Furosemide
- Hydrochlorothiazide
- Hydroflumethiazide
- Indapamide
- Methyclothiazide
- Metolazone
- Polythiazide
- Quinethazone
- Spironolactone
- Triamterene
- Trichlormethiazide

## URINE COLLECTION PROCEDURES

When the player arrives at the collection site, the collector will ensure that the player is positively identified through presentation of photo ID or identification by a team representative. If the player's identity cannot be established, the collector shall not proceed with the collection.

The player will be asked to select a sealed urine specimen cup. The player will then provide his urine specimen under the direct observation of the collector.

The collector shall ensure that the player has provided a urine specimen of sufficient volume for accurate testing. If such a sample cannot immediately be provided by the player, he shall be instructed to remain at the testing site for a reasonable period of time until he can provide such a specimen. Once the specimen has been obtained, the player will select a sealed specimen kit, which contains two bottles. The collector, in the presence of the player, will pour the specimen into two bottles. One bottle will be used as the primary or "A" specimen and the other will be used as the split or "B" specimen. The specimen bottles will be sealed with tamper-proof seals in the presence of the player. The seals will contain a unique identification number that corresponds to the number on the chain of custody form.

The player and collector will complete the chain of custody form (which may be in hard copy or electronic form) that documents the handling of the specimen. The collector will note any irregularities concerning the specimen on the chain of custody form. Both the player and collector will sign the chain of custody form. The kit will be sealed and sent via overnight courier to the laboratory for testing. If a hard copy chain-of-custody form is used, it will be included in the kit containing the two specimens that is sent by overnight courier to the laboratory. If an electronic chain-of-custody form is used, it will be sent to the laboratory electronically.

Once the specimens arrive at the laboratory, the primary specimen will be analyzed. If the primary specimen tests positive, the split sample will be placed in frozen storage and will be available for testing by a different laboratory, if requested by the player.

## STEROIDS, PERFORMANCE-ENHANCING DRUGS AND MASKING AGENTS CONFIRMATORY LABORATORY ANALYSIS LEVELS

All SPEDs (including Human Growth Hormone in its synthetic form), except those listed below, at any detectable level.

- Ephedra/Ephedrine 10 mcg/ml
- Methylephedrine 10 mcg/ml
- Nandrolone 2 ng/ml
- Norpseudoephedrine 5 mcg/ml
- Phenylpropanolamine (PPA) 25 mcg/ml
- Pseudoephedrine 25 mcg/ml
- Testosterone 4:1 t/e ratio