# 

## FORM OF CONFIDENTIALITY AGREEMENT

[Date]

National Basketball Players Association  
310 Lenox Avenue  
New York, NY 10027  

Re: Confidentiality Agreement

Gentlemen:

This will confirm the agreement of the National Basketball Players Association ("Players Association") (on behalf of itself and its employees, officers and outside advisors) to maintain the confidentiality of all Confidential Information (as defined in Paragraph 6 below) in connection with the audit, with respect to the 20__-20__ Salary Cap Year, of (i) the National Basketball Association ("NBA") League Office, (ii) any NBA team that the parties agree is to be included in such audit with respect to such Salary Cap Year (the "Team(s)"), and (iii) the expenses incurred in connection with proceeds that come within Article VII, Section 1(a)(1)(viii) of the Collective Bargaining Agreement ("CBA") entered into July 29, 2005, between the Players Association and the NBA (collectively, the "Audit"). Capitalized terms not defined herein shall have the meaning ascribed to such terms in the CBA.

1. The NBA and the Team(s) shall make available Confidential Information for purposes of the Audit based on the representation of the Players Association that it (and its employees, officers and outside advisors) shall comply with the terms of this Confidentiality Agreement at all times during and after the Audit. To that end, before any employee, officer or outside advisor of the Players Association may be permitted to review any Confidential Information, the Players Association shall require such employee, officer or outside advisor to agree, in writing (in the form of acknowledgment annexed hereto), to comply with the terms of this Confidentiality Agreement, and the Players Association shall promptly provide copies thereof to the NBA.

2. The Players Association shall maintain the absolute confidentiality of all Confidential Information at all times and shall not disclose to any person or entity, except as permitted herein, any Confidential Information. The Players Association agrees that it may use or refer to Confidential Information only during the course of the Audit and solely for the purpose of conducting the Audit in accordance with the terms and conditions of the CBA and this Confidentiality Agreement, and that Confidential Information may not be used or referred to by the Players Association (or any of its employees, officers and outside advisors), at any time, for any purpose other than to conduct the Audit in accordance with the terms and conditions of the CBA and this Confidentiality Agreement. The Players Association (and its employees, officers, NBA team player representatives ("Player Representatives") and outside advisors) shall not disclose, disseminate or provide any Confidential Information to any other person or entity (including NBA players who are not officers of, or Player Representatives for, the Players Association and any representative of any player), at any time, for any purpose; provided, however, that the Players Association may only disclose, disseminate or provide a summary of Confidential Information to Player Representatives in aggregate form without identifying any specific information (e.g., by sponsor). Notwithstanding anything to the contrary in this Confidentiality Agreement, the Players Association shall not be deemed to have violated any provision herein if the Players Association discloses to such third party that the Audit is being undertaken and that the Players Association is subject to a confidentiality agreement and, therefore, not permitted to discuss the Audit. The foregoing shall not foreclose the Players Association from disclosing Confidential Information during the course of a proceeding before the System Arbitrator, an appeal to the Appeals Panel of an award of the System Arbitrator and a judicial action to enforce any such proceeding or award.

3. The Players Association shall adopt and implement such procedures to insure the confidentiality of Confidential Information as would be employed by a reasonable and prudent person to safeguard the confidentiality of his or her own most confidential information, or, if more stringent, such procedures as are employed for such purposes by the Players Association. Such procedures shall include, but not be limited to,steps to insure that such Confidential Information is disclosed only to those Players Association employees and officers and, subject to the restrictions set forth in Paragraph 2 above, Player Representatives who have a need to have access to such Confidential Information and only for the purpose of conducting the Audit in accordance with the terms of the CBA and this Confidentiality Agreement. The foregoing shall not foreclose the Players Association from disclosing Confidential Information during the course of a proceeding before the System Arbitrator, an appeal to the Appeals Panel of an award of the System Arbitrator and a judicial action to enforce any such proceeding or award.

4. The Players Association agrees that no copies of Confidential Information made available by the NBA and the Team(s) may be removed from the NBA's or the Team(s)' offices (as applicable).

5. If the Players Association is required by governmental or judicial authorities (by oral questions, interrogatories, requests for information or documents, subpoena, civil investigative demand or similar process) to disclose any Confidential Information, it shall provide the NBA and/or the Team(s) with prompt notice so that the NBA and/or the Team(s) may seek an appropriate protective order. If, in the absence of a protective order, the Players Association is, after giving notice in accordance with the preceding sentence, compelled to disclose Confidential Information or else stand liable for contempt or suffer other censure or penalty, the Players Association may disclose only such Confidential Information as is necessary to avoid such liability without incurring liability hereunder.

6. For purposes of this Confidentiality Agreement, "Confidential Information" shall mean all documents, materials and other information reviewed or made available (whether in written or oral form) in connection with the Audit (including, without limitation, all documents, materials and other information made available by PricewaterhouseCoopers, LLP), and shall include all excerpts, extracts, summaries and contents thereof and notes taken during the Audit; provided, however that Confidential Information shall not include information that (a) is or becomes generally available to the public other than as a result of disclosure by the Players Association (including Players Association affiliates or representatives), (b) was available to the Players Association prior to its disclosure by the NBA or the Team(s) (as applicable), or (c) becomes available to the Players Association from a source other than the NBA or the Team(s), provided that such source is not bound by a confidentiality agreement with the NBA, the Team(s) or the Players Association.

7. The Players Association acknowledges that the terms and conditions contained in this Confidentiality Agreement are reasonable and necessary to protect the legitimate interests of the NBA and the Team(s), do not cause the Players Association undue hardship, and that any violation of the provisions of this Confidentiality Agreement or disclosure of any Confidential Information without the NBA's or the Team(s)' (as applicable) prior written consent will result in irreparable injury to the NBA and/or the Team(s) for which there is no adequate remedy. Accordingly, in the event of any such violation or disclosure, the NBA and/or the Team(s) shall be entitled to preliminary and permanent injunctive relief from any federal or state court of competent jurisdiction located in New York, New York, and the Players Association hereby consents to, and waives any objection to, venue and jurisdiction in such courts. In addition, the Players Association shall indemnify and hold harmless the NBA and its member teams and their respective affiliates, owners, directors, governors, officers and employees, and the successors, assigns and personal representatives of the foregoing parties ("NBA indemnified parties"), from and against all liability, damages and costs (including attorneys fees) arising out of any claim asserted against any NBA indemnified party relating to any use or disclosure of Confidential Information by, or the violation of this Confidentiality Agreement by, the Players Association (or any of its employees, officers, Player Representatives and outside advisors), provided that: (a) the Players Association is given prompt notice of any such claim; (b) the Players Association has the right to approve counsel and/or has the opportunity to undertake the defense of such claim; and (c) the indemnified party does not admit liability with respect to and does not settle such claim without the prior written consent of the Players Association. The Players Association also agrees that the relief provided for in this Paragraph 7 shall be cumulative and in addition to any other rights or remedies to which the NBA and the Team(s) may be entitled.

8. This Confidentiality Agreement is the final and complete agreement between the parties with respect to its subject matter. Any waiver of or modification to this Confidentiality Agreement must be in a writing and signed by each party. Any waiver in any particular instance of the rights and limitations contained herein shall not be deemed and is not intended to be a general waiver of any rights or limitations contained herein and shall not operate as a waiver beyond the particular instance.

9. This Confidentiality Agreement shall be governed by and construed and enforced in accordance with the laws of the State of New York, without giving effect to the principles of conflicts of law thereof.

If the foregoing coincides with your understanding of our agreement, please sign the enclosed copy of this letter and return it to me.

|                                         |
| :-------------------------------------- |
| NATIONAL BASKETBALL ASSOCIATION         |
| By: ___________________________________ |
|                                         |
| AGREED TO AND ACCEPTED:                 |
| NATIONAL BASKETBALL PLAYERS ASSOCIATION |
| By: ___________________________________ |

\newpage

**ACKNOWLEDGMENT**

The undersigned hereby acknowledges that I have read the Confidentiality Agreement between the National Basketball Players Association and the National Basketball Association dated _____________, 20___, and agree to comply with all of the terms and conditions contained therein.

Date: ________________________
By:___________________________
Name:_________________________
Title:__________________________

The National Basketball Players Association hereby acknowledges that the person identified above is an employee, officer, or outside advisor of the National Basketball Players Association.

National Basketball Players Association
Date:___________________________
By:_____________________________
Name:__________________________

\newpage

## EXHIBIT J-2

December 8, 2011

Mr. G. William Hunter  
Executive Director  
National Basketball Players Association  
310 Lenox Avenue  
New York, New York 10027  

Dear Billy:

This will confirm our agreement that the attached accounting procedures are the procedures that will be in effect for purposes of Article VII, Section 10 of the Collective Bargaining Agreement entered into on December 8, 2011, unless such procedures shall be modified by agreement of the parties.

If the foregoing coincides with your understanding of our agreement, please sign this letter in the space provided below.

Sincerely,  
/s/ <u>RICHARD W. BUCHANAN</u>  
Richard W. Buchanan  

AGREED TO AND  
ACCEPTED:  

NATIONAL BASKETBALL PLAYERS ASSOCIATION  

By:  
/s/ <u>G. WILLIAM HUNTER</u>  
G. William Hunter  
Executive Director  

\newpage

### Minimum Procedures To Be Provided By The Accountants

<U>**General.**</U>

- The Audit Report (and any Interim Audit Report or Interim Escrow Audit Report) must be prepared in accordance with the relevant terms of the Collective Bargaining Agreement ("CBA"), which should be reviewed and understood by all auditors.
- The Basketball Related Income Reporting Package and instructions should be reviewed and understood by all auditors.
- All audit workpapers should be made available for review by representatives of the NBA and Players Association prior to issuance of the report.
- A summary of all audit findings (including any unusual or non-recurring transactions) and proposed adjustments must be jointly reviewed with representatives of the NBA and Players Association prior to issuance of the report.
- Any problems or questions raised during the audit should be resolved jointly with representatives of the NBA and Players Association (or by the Accountants, to the extent called for under the CBA).
- All estimates should be reviewed in accordance with the CBA. Estimates are to be reviewed based upon the previous year's actual results and current year activity. All estimates should be confirmed with third parties when possible.
- Revenue and expense amounts that have been estimated should be reconfirmed with the controller or other team representatives prior to the issuance of the Audit Report on or before the last day of the Moratorium Period.
- Where appropriate, team and NBA revenues and expenses should be reconciled to audited financial statements.
- All reporting packages and supporting schedules are to be completed in U.S. dollars.
- The Auditors may consider, but are not bound by, the value attributed to or treatment of revenue or expense items in prior years.
- Auditors should be aware of revenues excluded from BRI. The Teams should be instructed to make available to the Auditors all information necessary to determine categories of revenues they have excluded from BRI. Questions regarding whether revenues or expenses are includable or excludable from BRI should be reviewed with both parties to determine proper treatment. Auditors should perform a review for revenues improperly excluded from, or included in, BRI.

<U>**Team Salaries**</U>

- Trace amounts to the team's general ledger or other supporting documentation for agreement.
- Foot all schedules and perform other clerical tests.
- Examine an appropriate sample of player contracts, noting agreement of all salary amounts, in accordance with the definition of Salary in the CBA.
- Compare player names with all player lists for the season in question.
- Inquire of controller or other representative of each team if any additional compensation was paid to players and not included on the schedule, and, if so, whether or not such amounts were paid for basketball services. Also inquire if any business arrangements were entered into by the team or team affiliate with players or their affiliates, including with retired players who played for the team within the past five (5) years.
- Review performance bonuses to determine whether such bonuses were actually earned for such season.
- Review signing bonuses to determine if they have been properly allocated in accordance with the terms of the CBA.
- Confirm that, where provided in the CBA, certain contracts have been averaged.

<U>**Benefits**</U>

- Trace amounts to the team's general ledger or other supporting documentation for agreement.
- Foot all schedules and perform other clerical tests.
- Investigate variations in amounts from the prior year through discussion with the controller or other representative of the team.
- Review each team's insurance expenses for premium credits (refunds) received from Planet Insurance Ltd. (owned by Teams) and the players' medical and dental insurance carriers (amounts can be obtained from League Office).
- Review League Office supporting documentation with respect to Benefits.

<U>**Basketball Related Income**</U>

- Trace amounts to team's general ledger or other supporting documentation for agreement.
- Foot all schedules and perform other clerical tests.
- Trace gate receipts to general ledger and test supporting documentation where appropriate.
- Gate receipts should be reviewed and reconciled to League Office gate receipts summary.• Verify amounts reported as luxury suite revenues with supporting documentation from the entity that sold, leased or licensed such luxury suites.
- Verify amounts reported as complimentary tickets and tickets traded for goods or services with supporting documentation from the team.
- Trace amounts reported for novelties and concessions, game parking, game programs, Team sponsorships and promotions, arena signage and arena club sales to general ledgers and test supporting documentation where appropriate.
- Where reported amounts include proceeds received by a Related Party, verify the amounts reported with supporting documentation from the Related Party.
- Examine the National Television and Cable contracts at the League Office, and agree to amounts reported.
- Review, at League Office, expenses deducted from the National contracts in accordance with the terms of the CBA. Review supporting documentation and test where applicable.
- Examine local television, local cable and local radio contracts. Verify to amounts reported by teams.
- When local broadcast revenues are not verifiable by reviewing a contract, detailed supporting documentation should be reviewed and tested.
- All loans, advances, bonuses, etc. received by the League Office or its teams should be noted in the report and included in BRI where appropriate.
- Schedules of NBA Radio, NBA TV, international broadcast, NBA Media Ventures, copyright royalty revenues and expenses should be obtained from the NBA. Schedules should be verified by agreeing to general ledgers and examining supporting documentation where applicable.
- Schedules of revenues and expenses reported by Properties for sponsorship, NBA related revenues from NBA Entertainment, and NBA Special Events should be obtained from the NBA. Schedules should be verified by agreeing to general ledgers and examining supporting documentation where applicable.
- Net exhibition revenues and expenses should be verified to supporting documentation where appropriate.
- All amounts of other revenues should be reviewed for proper inclusion/exclusion in BRI. Test appropriateness of balances where appropriate.
- Determine the ratio of expenses to revenues for those categories of proceeds that come within the provisions of Article VII, Section 1(a)(6) of the CBA and determine the extent to which expenses should be disallowed, if at all, pursuant to the provisions of that Section.

<U>**Playoff Revenues**</U>

- All sources of playoff revenues and expenses should be verified per the procedure outlined for Basketball Related Income.
- Because of the late timing of the Playoffs, special attention should be given to revenue and expense estimates.
- Playoff gate receipts should be recorded net of Taxes. Payments made to the Playoff Pool should not be deducted. Odd game payments should not be either deducted by the paying team or recorded by the receiving team.
- Other playoff expenses should be reviewed in accordance with the terms of the CBA.• Team expenses paid by the League Playoff Pool, including travel expenses, should not be deducted by teams.
- Review League Office supporting documentation as to expenses deducted from the Playoff Pool.

<U>**Related Party Transactions**</U>

- Inquire of the controller or other representative of the team what, if any, Related Parties exist, and discuss with the parties what, if any, amounts should be included in BRI.
- Review information provided as to the team's Related Parties and revenues that arise from Related Party transactions, and request supporting details where appropriate.
- Any revenue from a Related Party should be reviewed with both parties to determine proper treatment under the CBA.
- Request that details be provided, where appropriate.
- Prepare a summary of any changes, corrections or additions to Related Party information previously reported.
